### ISSUE TITLE
node module netstats errors

### ISSUE THREAD

**Issue by BeerK0in** [BeerK0in/gunbot-monitor#14]
After some hours on OSX this error stops gmon:

```
gunbot-monitor/node_modules/node-netstat/lib/utils.js:72
    stream.on('data', function (data) {
          ^

TypeError: Cannot read property 'on' of undefined
    at exports.emitLines (gunbot-monitor/node_modules/node-netstat/lib/utils.js:72:11)
    at exports.async (gunbot-monitor/node_modules/node-netstat/lib/activators.js:48:5)
    at module.exports (gunbot-monitor/node_modules/node-netstat/lib/netstat.js:63:9)
    at NetData.calculateConnections (gunbot-monitor/src/modules/netData.js:35:5)
    at Timeout.interval.setInterval [as _onTimeout] (gunbot-monitor/src/modules/netData.js:30:44)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
Add try catch.

**Comment by BeerK0in** [comment]
Should be fixed in 0.0.30

**Comment by BeerK0in** [comment]
new error now:


```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn netstat ENFILE
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by BeerK0in** [comment]
Also happens on archlinux and ubuntu (16.04.).

**Comment by jbogatay** [comment]
Finally had a chance to look into this.  It would appear gmon is leaking file descriptors, and it's unrelated to netstat.  Get the pid of gmon and run this:

    while true ; do lsof -p 17273 | wc -l ; sleep 5 ; done

Change 17273 to the pid of gmon.   It steadily climbs until it finally blows.   Will try and look further when I get a chance.

**Comment by jbogatay** [comment]
I thought it might be the fs.stat call (which really isn't needed) but it's not.

It's a bug in the read-last-lines library.  It never closes file handles.
[issue](https://github.com/alexbbt/read-last-lines/pull/8)

Have to see if there are any competing libraries, or the difficulty of roll-your-own.

**Comment by BeerK0in** [comment]
Updated version supports Gunbot v9 now. No need for the read-last-lines library anymore.
