### ISSUE TITLE
Just had the following error

### ISSUE THREAD

**Issue by vbootstrap** [BeerK0in/gunbot-monitor#19]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn netstat EMFILE
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jbogatay** [comment]
I've got about 3-4 of these on my archlinux box -- haven't seen any on an ubu box.

**Comment by vbootstrap** [comment]
Yeah I am running Ubu 16.04

**Comment by BeerK0in** [comment]
Thanks for the report. The bug is tracked in issue #14 - so I'll close this one.
